# Generated by Django 4.2.18 on 2025-02-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(default='2025-02-10', verbose_name='Дата начала курса'),
            preserve_default=False,
        ),
    ]
